variable "access_key" {}
variable "secret_key" {}
variable "key_name" {}
variable "region" {}
variable "ami" {}
variable "vpc_name" {}
variable "vpc_cidr_block" {}
variable "subnet1_name" {}
variable "subnet1_cidr_block" {}
variable "subnet2_name" {}
variable "subnet2_cidr_block" {}
variable "pub_subnet1" {}
variable "pub_subnet2" {}
variable "instance_type" {}
variable "sg_name" {}
variable "jenkins_main_server" {}
variable "app_server" {}
variable "jenkins_agent_server" {}
variable "dep5_1_route_table" {}
variable "igw_name" {}
variable "route_table_cidr_block" {}